[build]
  publish = "."
  functions = "src/api"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/shopping-lists.html"
  to = "/src/pages/shopping-lists.html"
  status = 200

[[redirects]]
  from = "/create-shopping-list.html"
  to = "/src/pages/create-shopping-list.html"
  status = 200

[[redirects]]
  from = "/view-shopping-list.html"
  to = "/src/pages/view-shopping-list.html"
  status = 200

[[redirects]]
  from = "/shopping-welcome.html"
  to = "/src/pages/shopping-welcome.html"
  status = 200

[dev]
  port = 8888
  publish = "."
  functions = "src/api"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"