#!/usr/bin/env node

/**
 * Environment Variable Injection Script
 * 
 * This script injects environment variables into a JavaScript file
 * that can be loaded by the browser.
 * 
 * Usage: node scripts/inject-env.js
 */

const fs = require('fs');
const path = require('path');

// Get environment variables
const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';
const NODE_ENV = process.env.NODE_ENV || 'production';

// Generate the env.js file
const envFileContent = `/**
 * Auto-generated environment configuration
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated at: ${new Date().toISOString()}
 */

window.ENV = {
    SUPABASE_URL: '${SUPABASE_URL}',
    SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}',
    NODE_ENV: '${NODE_ENV}'
};

console.log('🔧 Environment variables loaded from env.js');
`;

// Write to src/utils/env.js
const outputPath = path.join(__dirname, '..', 'src', 'utils', 'env.js');
fs.writeFileSync(outputPath, envFileContent, 'utf8');

console.log('✅ Environment variables injected successfully');
console.log(`   Output: ${outputPath}`);
console.log(`   SUPABASE_URL: ${SUPABASE_URL ? '✓ Set' : '✗ Missing'}`);
console.log(`   SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY ? '✓ Set' : '✗ Missing'}`);
console.log(`   NODE_ENV: ${NODE_ENV}`);

// Exit with error if required variables are missing
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('');
    console.error('⚠️  WARNING: Missing required environment variables!');
    console.error('   Please set SUPABASE_URL and SUPABASE_ANON_KEY in your deployment platform.');
    console.error('   For Netlify: Site settings → Environment variables');
    console.error('');
    console.error('   The app will not work correctly without these variables.');
    console.error('');
}
